language: python
sudo: false

virtualenv:
  system_site_packages: false

cache:
  directories:
    - $HOME/virtualenv

matrix:
  include:
    - python: "2.7"
    - python: "3.6"

addons:
  apt:
    packages:
      - libpng-dev
      - libtiff4-dev
      - libfftw3-dev
      - libhdf5-serial-dev
      - cmake
      - gsl-bin
      - libgsl0-dev
      - swig

before_install:
  - export PY_SITE=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
# Python packages
  - pip install numpy
  - pip install scipy
  - pip install h5py
# Install libspimage
  - cd $HOME/build/FXIhub/libspimage
  - mkdir build
  - cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_CUDA=OFF -DPYTHON_WRAPPERS=ON -DCMAKE_INSTALL_PREFIX=${HOME}/virtualenv/python$TRAVIS_PYTHON_VERSION/ -DPYTHON_INSTDIR=${PY_SITE} ..

install:
    - make VERBOSE=1
    - make install

script:
  - echo $LD_LIBRARY_PATH
  - echo $PYTHONPATH
# Testing imports
  - python -c "import numpy; print(numpy.__file__)"
  - python -c "import scipy; print(scipy.__file__)"
  - python -c "import h5py; print(h5py.__file__)"
  - python -c "import spimage; print(spimage.__file__)"